### ISSUE TITLE
Implement Load/Dump HBZones for Ease With Long Microclimate Map Runs

### ISSUE THREAD

**Issue by jankiv** [mostaphaRoudsari/honeybee#624] opened 2017-05-04 13:19 UTC
Hi @chriswmackey Thanks for looking into the "make adiabatic" component (issue #623). I updated the file on my end, but I think in doing so I crashed something else. I've been troubleshooting it for quite some time. I even rebuilt the script I was working on. The script works once, but when I plug in an analysis period or make changes to the EnergyPlus parameters and let it run overnight it freezes and crashes. Errors are shown below. 

The error I am getting says the comfort recipe doesn't have any surface temperatures in the CSV file but they are there. I am able to read annual values for both indoor and outdoor temperatures for all 29 surfaces in the zone.
Any guess as to what the problem can be? I'm guessing it has to be a bug with the output of the comfort recipe or the panel that accepts the comfort recipe. It doesn't seem to be an issue with my computer memory or hard drive space either since I tried restarting both Rhino and my computer between subsequent runs. 

![image](https://cloud.githubusercontent.com/assets/25178111/25705010/c010763c-30a9-11e7-912a-87ff3499916a.png)

![image](https://cloud.githubusercontent.com/assets/25178111/25705124/33985566-30aa-11e7-8d15-1569ff019bab.png)

![image](https://cloud.githubusercontent.com/assets/25178111/25705132/3a7c22ae-30aa-11e7-96f9-dd43d3125238.png)

![image](https://cloud.githubusercontent.com/assets/25178111/25705136/4043a50e-30aa-11e7-8148-521a5821e4cb.png)

![image](https://cloud.githubusercontent.com/assets/25178111/25705140/4508f1de-30aa-11e7-8603-5751af4b1fc1.png)

**Comment by jankiv** [comment] 2017-05-04 19:00
I think this could be the problem.

I am running the energy model. Setting it to False. Then using a panel with the results file address instead of connecting the "resultFileAddress" output. 
![image](https://cloud.githubusercontent.com/assets/25178111/25720224/26eafd48-30da-11e7-9111-d014e5c1e003.png)

**Comment by chriswmackey** [comment] 2017-05-06 12:21
@jankiv ,
It looks like the names of zone surfaces are not matching between your HBZones and the simulation results.  Are you plugging in the same exact zones into the "Run Energy Simulation" component as you are the ViewFactorCalculator?

**Comment by jankiv** [comment] 2017-05-06 12:52
Yup. The only change I make between the energy model run and the microclimate run is using a panel for the results address instead of the direct output from the energyplus component. 

----------
Janki A Vyas

**Comment by chriswmackey** [comment] 2017-05-06 19:06
Ok.  So , assuming everything is working once you reconnect the resultFile to the EP component, I am closing out the issue.  Feel free to reopen it if I'm misunderstanding.

**Comment by jankiv** [comment] 2017-05-15 19:03
@chriswmackey #624
Hi, I'm not sure how to open this issue back up so I'm just responding here. Everything stops working when I use a panel with results file address to read in results at several points in the thermal comfort workflow. 

The first error occurs after the energy plus run. When I switch from the resultsFileAddress output to a panel with a file path prior to running Microclimate Map Analysis (which is what I was showing above). 
The only way it works is if I work sequentially running an energy model and then immediately running the microclimate map. If I run one, wait a day and then try to pull the energy model csv back in, it will not work. 

The second location where this occurs is when I try to Visualize Microclimate Map using previously run Simulations. Again, it only works if I am working on it sequentially without closing out of the file or referencing a previous run. 

Since these simulations are computationally expensive and tend to surpass my working hours, I'm having trouble analyzing the simulations I let run overnight.\
![image](https://cloud.githubusercontent.com/assets/25178111/26074313/4623674c-397f-11e7-87bb-9494c7afd4ee.png)

For example this was working this morning, but now when I bring in the radiant temperature csv file it refuses to work.

**Comment by jankiv** [comment] 2017-05-15 19:04
Here is the csv file I am using, i am not able to upload the GH file

**Comment by chriswmackey** [comment] 2017-05-16 17:31
@jankiv ,

The first issue that you note is by design.  The microclimate maps work by matching the names of surfaces between the HBZones and the energy simulation results.  When you re-run your GH script and you have not named all of the surfaces, the script will generate new random names for all of the surfaces and things will no longer match.  At some point I'll see if I can finish the [Dump and Load HBZones components](https://mostapharoudsari.gitbooks.io/honeybee-primer/content/text/components/Dump_Honeybee_Objects.html), which will allow you to save HBZones to a standalone file and load them back exactly as they were.  This way, you can have matching names.

The second issue seems to be because you have connected an analysis period for a time range that you did not run. Disconnect the analysis period or connect a correct one and it should work.

You have to post links to files on Github by uploading them to dropbox/google drive and sharing links here.

**Comment by jankiv** [comment] 2017-05-16 18:05
I named the surfaces but only by type, so if there was more then one geometry then the duplicates are autonamed by EnergyPlus. So if I convert the names to a multiline panel and name each surface with unique identifiers it should solve the problem I am having right? 
Thanks,  JV

**Comment by chriswmackey** [comment] 2017-07-26 13:25
This has new been implemented.  You can now write HBZones to a file or write the viewFactorInfo to a file and load up zones again later.

**Closed by chriswmackey** 2017-07-26 13:25 UTC
Labels: EnergyPlus, enhancement, OpenStudio
