### ISSUE TITLE
Energy and Comfort Simulations - North issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#612] opened 2017-03-22 11:51 UTC
Hi,
I'm not sure by now where to report about this, so i'll start here.
The thing is that the results obtained when the North input is provided (different than the 0 value default) in the HB_exportToOpenStudio are problematic.
All things related to LB and the North are fine and proved. While in HB+E+ things are more like a black box.
We are working with a student on a thermal comfort research for old buildings. We are building a case to prove that the model is well calibrated (for simulation). The model consists of 3 thermal zones (South with a bigger window, Corridor in the middle and North with a smaller window). We want to test the model for 4 orientations. And here is the where the issue arises. The results are different when you physically rotate the model than where you rotate the north direction. We started from the later, but then i noticed strange behavior in the results and tried the rotation of the model. So here i am.
I'm not sure if the problem is with E+, then i need to report on their forum, or with HB.
This file:
> https://www.dropbox.com/s/x2s1rsbzg58ck6t/Compare%20North.pdf?dl=0
shows what am i talking about. I have 2 tables, one for summer and one for winter. The left columns show the results of the model rotated and the right one the north rotated. Notice, specially for the early and late hours, the direction of the hottest areas (i'm showing Operative Temperature and Adaptive comfort maps). Of course is things were working as expected both left and right columns MUST be similar. The Operative Temperature maps are the best to look at.

I'll appreciate your thoughts.
If the problem is with E+ i thing many people will be in trouble.

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment] 2017-03-25 21:04
Hi Abraham, Is this only an issue with OpenStudio or also happens with the EnergyPlus component?
Meanwhile I will check the idf files in both case to make sure the exported idf file matches in both cases and report back here.

**Comment by mostaphaRoudsari** [comment] 2017-03-25 23:15
I checked and there is a discrepancy between OpenStudio and EnergyPlus components only when using a vector. The OpenStudio component doesn't convert the values correctly.

![image](https://cloud.githubusercontent.com/assets/2915573/24326809/900f8fbc-118d-11e7-8c04-6a690182c271.png)

and this is why:
![screenshot 9](https://cloud.githubusercontent.com/assets/2915573/24326883/62c5167e-118f-11e7-85dc-1532235660bd.png)

**Comment by mostaphaRoudsari** [comment] 2017-03-25 23:21
@ayezioro The type is fixed now. I'm keeping this open as I'm not sure the type was the reason for the bug. Let us know your thoughts.

**Comment by chriswmackey** [comment] 2017-03-26 04:26
Oh, gosh.  This seems like an error that must have come about long ago when the north input was first added to the component.  I can confirm that this should fix the issue because the OpenStudio component uses the same function to read the north vector as all of the Ladybug components.

**Comment by ayezioro** [comment] 2017-03-26 09:41
Hi,
I started checking the fix, but ... a new issue arise: The resultsFileAddress output is giving a Null result (the other outputs are ok):
![capture](https://cloud.githubusercontent.com/assets/7526023/24330168/70337926-1221-11e7-8d1a-572f938f88b4.JPG)

Any ideas?
-A.

**Comment by ayezioro** [comment] 2017-03-26 13:39
Update on my last comment. Tried another file, with the updated OS component and the output is fine.
As for the previous case, even though the output says Null, the CSV is produced and is functional/
So i don't know why this happens.
I'll try to restart the machine. Maybe it is related (tried already closing GH and Rhino).
-A.

**Comment by mostaphaRoudsari** [comment] 2017-03-26 13:41
Thanks Abraham. I didn't change anything but the north input type: https://github.com/mostaphaRoudsari/honeybee/commit/43f703f74137d6d2184cfcd6f1a75abd6ddfd89f so if the error persists that should be for another reason.

**Comment by chriswmackey** [comment] 2017-03-27 00:05
@ayezioro ,
Glad that everything is working and I think the issue that you experienced is the result of another change I made recently where I changed the output name to be resultFileAddress instead of resultsFileAddress (to be consistent with the E+ component):
https://github.com/mostaphaRoudsari/honeybee/commit/e7e75ee765b8d1ede64b73fc2fdd562b885b79e5
-Chris

**Comment by ayezioro** [comment] 2017-03-27 03:06
Hi Chris,
I've just updated the file and needed to reinsert the OS. Is now working.
I'm in the process of checking, so it is too soon to close this. What i can say so far is that without changing the north the results changed from the previous ones (i mean with the north up. Don't know what tosay.
I'll report more detailed later this week.
Thanks,
-A.

**Comment by chriswmackey** [comment] 2017-03-28 00:19
Ok.  Sorry for closing the issue prematurely.

**Comment by ayezioro** [comment] 2017-03-28 08:40
Ok guys,
I think i get why the problem is happening ... and it is happening.
This is the last checking i did:
https://www.dropbox.com/s/qy8gzalzb0jqduh/Compare%20North_TCW.pdf?dl=0
You can see there that it was expected to get the same results for both cases (left: north upwards; right: north rotated 90 and the model rotated also). The expected results were supposed to be the same (hope you agree). But they aren't. From the Operative Temperature maps you can see that the picture is wrong, like the rotation is not happening.

My conclusion is the following: There is no option but this situation to happen. The reason: The ONLY place where you set the north is the OS or E+ run simulation. This is only registered in the IDF file as a number, but the model itself is not rotated. After you get the results, there are other places where you are still dealing with the model (IndoorViewFactor for instance). Those components don't know about the north setting. Moreover, i suspect they assume the north is pointing upwards, in the best case, or not relating to the north at all as a function to take into account.

I don't know how "easy" is going to be to fix this one, but until then my only recommendation is to rotate the model and not using the north input.
I checked some results using the E+ component. The comfort results are a bit different. There are some zones that the difference is big (the middle zone in the example). The average result is similar, but not the same.

As for the HB_rotate (and probably the other transformation components), i've found also a bug, which i'll report in a separate issue.

Makes sense?
Thanks,
-A.

**Comment by ayezioro** [comment] 2017-03-28 13:11
A small update,
I need to do some homework again. I see now that the comfort components have a north input ... which i didn't used (shame on me). I'll check and will report back.
Not sure how they deal with the context, in case there is one (it is accounted in the IndoorViewFactor?
-A.

**Comment by ayezioro** [comment] 2017-03-28 14:52
This is the "report back".
I created a false alarm. Now that i connected the north input wit the comfort recipe component the results are as expected. See file:
https://www.dropbox.com/s/4psiej7nwihclsz/Compare%20North_TCW_01.pdf?dl=0
What remains open is the other discussion about the HB_Rotate.
Thanks,
-A.

**Comment by chriswmackey** [comment] 2017-03-29 03:59
@ayezioro ,
Glad that everything is working out.  I know that makes for easy mistakes to have 2 north inputs but it seemed to be the best way of guaranteeing flexibility at the time that I was putting it all together.  In any case, feel free to close out this issue and I will fix the other one that you opened.

**Closed** 2017-03-29 04:22 UTC
Labels: bug, OpenStudio
