### ISSUE TITLE
Honeybee IES Luminaire Component Dimensions Error

### ISSUE THREAD

**Issue by jankiv** [mostaphaRoudsari/honeybee#601] opened 2017-02-10 13:45 UTC
Hi, I am trying to run an electrical lighting simulation for light trespass from multiple indoor lighting types. 
I have IES files for three lighting types, of which two are recessed fixture types. I am unable to run the simulation because of the following error: 1. Solution exception:The luminous dimensions for the specified luminaire are (-0.5,0.0,0.0). This format, which is neither rectangular nor circular, is not supported currently. 
I am assuming since the fixture is recessed there is a negative value for the dimensions, thus the error. Or is there a special way to model it?

**Comment by chriswmackey** [comment] 2017-02-10 15:35
@jankiv ,
I thought that I had revised the component so that it would still run in cases of different luminaire geometry but I could be mistaken.  If you could post a link to the IES file that you are trying to run, I can recreate the issue on my machine and fix the issue.

-Chris

**Comment by jankiv** [comment] 2017-02-15 17:10
Thanks @chriswmackey , 

The IES files I was using is as follows: http://www.intenselighting.com/product/iholc6dr/

I ended up downloading IESViewer (http://www.photometricviewer.com/?i=1) and editing the IES file to change the luminare dimensions from negative to positive, as well as revising the zero values.  I think the component doesn't like negative or zero values because I was able to view the IES file in IESViewer with no problems. 

Additionally, I used dimensions for the luminare housing from the submittal sheet. I tried simulating both SI and IP dimensions, as it was unclear if the component was using the rhino scene units or units per the IES file. But changes in luminare dimensions (SI vs IP) did not effect foot candles at the analysis plane, so I am not sure if my hack to get it to work was appropriate or not.

**Comment by mostaphaRoudsari** [comment] 2017-02-15 17:47
cc: @sariths

**Comment by sariths** [comment] 2017-02-15 22:31
Hi @chriswmackey and @jankiv , 

The Honeybee scripts for electric lighting are based on IES L63-02. The luminous shape described in that ies file (-width, 0 , 0) is not defined in LM-63-02 and that is the cause of error. I tried out this file on a couple of different softwares and it seems that manufacturers assume the shape to be (-width, -width, 0) in such cases. 

Attached is a quick-fix for this issue. You can copy the IES luminaire component from that file and make it work. (https://www.dropbox.com/s/e2to7ill09jacow/iesFix.gh?dl=0)

@chriswmackey , @mostaphaRoudsari : I noticed that there is also a tiny bug in case the luminaire is a point source. I will key in a fix sometime within the next couple of weeks.

**Comment by jankiv** [comment] 2017-02-28 14:00
Thanks @chriswmackey and @sariths!
Just a quick followup question. Was it okay to modified the dimensions in the IES text file? Or did I end up unintentionally altering the results by changing the shape? Just wondering if I should rerun the analysis we did. Thanks, JV

**Comment by sariths** [comment] 2017-02-28 16:59
HI @jankiv , without seeing your gh file its hard to tell with absolute certainty. Since you mentioned that you were running a light trespass calculation, I assume that the light fixture is pretty far from where the measurement points are and therefore we can assume the five times rule (See the "Point Source Approximation" part [here](https://www.intl-lighttech.com/support/basic-light-measurement-principles-chapter-6-light-measurement-tutorial)). Since you've only altered the shape and not the distribution it is unlikely that a major change in results will be affected due to that.

**Comment by jankiv** [comment] 2017-02-28 17:43
Thanks @sariths! The links you've shared are very useful! Theyexplain how the photometric files are generated, so I can understand the what adjustments might be harmful vs helpful towards more accurate simulation.

**Comment by chriswmackey** [comment] 2017-03-14 23:17
@sariths  and @jankiv ,

I improved a bit upon your quick fix, @sariths , and I've changed the code such that Honeybee now accepts this type of IES file:
https://github.com/mostaphaRoudsari/honeybee/commit/c4e196b86e292caf78d6c13e188f8aa44c288119

Thank you both for finding this issue and working to fix it!
-Chris

**Closed by chriswmackey** 2017-03-14 23:17 UTC

**Comment by sariths** [comment] 2017-03-14 23:23
@chriswmackey , Thanks ! It is unlikely (despite what I promised initially) that I would have gotten to this any time soon.

**Comment by chriswmackey** [comment] 2017-03-14 23:39
Thank YOU, @sariths .  You did all of the heavy-lifting of figuring out what the luminaire should be.  I wouldn't have remotely known what type of convention they were using otherwise.
