### ISSUE TITLE
EnergyPlus and OpenStudio ideal air load system discrepancies

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#530] opened 2016-07-13 15:08 UTC
Hi there,

As I am about to change my definitions' simulation engine from EnergyPlus to OpenStudio (I read that this will happen in a close future), I did a simple comparison to see if the results were more or less the same.
I modelled a simple room and I figured out some discrepancies: as shown in the picture cooling, heating and lighting consumptions have changed significantly. Do you know why this happens?
Thank you.
![image](https://cloud.githubusercontent.com/assets/8501837/16808209/df7c413e-491b-11e6-9c64-d394816d78ac.png)

**Comment by mostaphaRoudsari** [comment] 2016-07-13 15:21
Hi @jacoposartore, Thanks for getting this started. To make sure we're comparing apples to apples can you check the idf files and see if they are using the same version of EnergyPlus? You can find it in the header of the file.

**Comment by chriswmackey** [comment] 2016-07-13 20:02
@jacoposartore ,
Thanks for posting the comparison.  If I had to make a guess, I think that the difference is not the result of any settings on the ideal air system because the lighting is affected too.  Rather, I think that the "Run Simulation" component and the "OpenStudio" component might be using different start week days of the year.  I think that the run simulation component uses Monday by default and the OpenStudio componet uses whatever is in the weather file.  I will check this out now.
In the meantime, please let me know the answer to Mostapha's questions and, if you could post a link to your GH file, there, that would help me pinpoint the issue better.
-Chris

**Comment by chriswmackey** [comment] 2016-07-13 21:17
@jacoposartore ,
Nevermind about posting an example file.  I was able to create a very similar situation myself.  I verified that I am using the same version of EnergyPlus (E+ 5.0) for both OpenStudio and standalone E+.  It turns out that there is a lot that does not match between the IDF generated by the Run Simulation component and that which is exported from OpenStudio.  In particular, there seem to be a number of features in the autosizing of the HVAC that OpenStudio and Run Simulation do differently.  I am going to try to investigate this over the next hour ans post back here.  My initial instinct is that OpenStudio's defaults are more correct (or at least they have more HVAC experts on their team than we do).  As such, I will probably end up defaulting to OpenStudio in most of the edits that I make.

@mostaphaRoudsari .  let me know if this plan sounds good.
-Chris

**Comment by chriswmackey** [comment] 2016-07-13 22:36
Ok.  I got the lighting to match.  It was the result of a glaring bug in the Export to OpenStudio component.
https://github.com/mostaphaRoudsari/Honeybee/commit/26b8679cbb66b0f6a7f06dd49c0688b9820c87e9

The remaining differences in heating/cooling seem to be the result of the system sizing parameters.  Namely, OpenStudio is sizing based on a design day and Run Simulation is sizing based on an extreme week.  Still, I have the heating values close to each other within 1% error and cooling matching within 3%.  I'll try to close this gap soon.
-Chris

**Comment by jacoposartore** [comment] 2016-07-14 07:39
@mostaphaRoudsari I checked the idf files and OpenStudio component is version 8.5 whereas the EnergyPlus one the 8.4. Can we use EnergyPlus 8.5? A couple of weeks ago I got an error from honeybee main component saying that it couldn't find any EnergyPlus installed (I had to revert to version 8.4)
@chriswmackey thank you for your investigations.

**Comment by jacoposartore** [comment] 2016-07-14 12:07
@mostaphaRoudsari this morning, as soon as I read your answer, I installed EnergyPlus 8.5 and it's working fine. Great, thank you!

**Comment by chriswmackey** [comment] 2016-07-14 14:42
@jacoposartore ,
I now have the HVAC system sizing protocol matching between the E+ and OS components, The resulting heating and cooling values are now matching within 1% but they are still not perfectly equal to one another.  I am not sure if we are going to be able to get them to match perfectly because the E+ component uses a template ideal air system while the OS component uses a complete ideal air system (with connections to zones, etc.).  I am going to investigate the zone sizing parameters and hopefully matching these will get the results to match better.  After that, there is not much more that I can do and so I will close out the issue then.
-Chris

**Comment by jacoposartore** [comment] 2016-07-14 14:59
@chriswmackey it seems a good plan to me!
1% difference is reasonable if compared to the previous 8-10%. 
Thank you! :+1:

**Comment by chriswmackey** [comment] 2016-07-14 16:16
@jacoposartore ,

I added in one last thing that brought the heating and cooling values a bit closer together.  The overall difference in heating and cooling is still around +/- 1% and this is because the full Ideal Air system that OpenStudio uses has a few more sizing specifications that can be assigned in comparison to the template Ideal Air system that the E+ component uses.  I think that it is best to keep things this way as the OpenStudio system is probably closer to what we would do in practice in terms of sizing.  However, the OS system is much more complicated to set up in comparison to the simple ideal air system and I think that many users might appreciate the E+ component's simplicity if they want to delve into the IDF.

Since you have signed off on a +/- 1% error, I am going to close out the issue.  Hopefully, this issue will be a good reference for anyone else who notices this mis-match.

-Chris

**Comment by jacoposartore** [comment] 2016-07-14 17:12
@chriswmackey,

I exedend this comparison to the other outputs available and everything seems fine under the 1% error except the glazingEnergyFlow (5% errror) and the surfaceEnergyFlow (40% error): as in the pictures some surfaces have similar energy flow across the whole year, other are much different (some flow balances are 50% lower in OS than EP).

![image](https://cloud.githubusercontent.com/assets/8501837/16848512/66f7644c-49f6-11e6-92cd-bf007102b53b.png)

![image](https://cloud.githubusercontent.com/assets/8501837/16848465/3a3cf804-49f6-11e6-9ffb-c8c6722fc10a.png)

**Comment by chriswmackey** [comment] 2016-07-15 02:14
@jacoposartore ,

I am getting some pretty good matching of values for surface and glazing energy flow with my file.  The energy Balances seem almost identical and the overall loss/gain through the envelope in the different months is fairly comparable:
![conductioncomaprison](https://cloud.githubusercontent.com/assets/5567574/16861613/55316f04-4a10-11e6-9f72-beafd8001044.JPG)


This said, I just made a change to the way that the OpenStudio file was writing out constructions and there's a chance that this might improve the issue here:
https://github.com/mostaphaRoudsari/Honeybee/commit/e917c2e706bff2b61bfe6dcd369d916a2188dfdc

Let me know if the problem gets any better after you update your components.
-Chris

**Comment by jacoposartore** [comment] 2016-07-15 07:43
@chriswmackey,

I just have updated my definition and completed the energy balance as you did. I also get that the results have a neglectable difference when comparing opaque and glazing conduction (see the images below). Very good!

![image](https://cloud.githubusercontent.com/assets/8501837/16866983/5faecf62-4a6f-11e6-9676-89cb72e8a61e.png)

![image](https://cloud.githubusercontent.com/assets/8501837/16867125/5f59c6ce-4a70-11e6-907a-fb3e555c2e62.png)

Why there is such a big difference, despite the surfaceEnergyFlow of the energy balance is the same that is used in the surface results?

**Comment by chriswmackey** [comment] 2016-07-18 18:43
@jacoposartore ,
I am reopening this issue because I think I know what is causing the discrepancy with the surfaces.  I am going to try to fix it shortly.  I'll post back here once I do so.

-Chris

**Comment by chriswmackey** [comment] 2016-07-18 20:46
@mostaphaRoudsari ,

Here is a file that shows the error:
https://www.dropbox.com/s/fiovhz0ogti9g5h/SurfaceEnergyMatching.gh?dl=0

It is definitely the mis-match in global geometry rules that is causing the error (LowerLeftCorner vs UpperLeftCorner).

-Chris

**Comment by chriswmackey** [comment] 2016-07-24 00:14
@jacoposartore ,

Let me thank you again for riggorously testing this and finding/reporting this discrepancy. I can see now that, had you not pointed out the difference in surface energy flow to us, there could have been a bug in OpenStudio that could have gone undetected for a very long time.

Needless to say, I have now fixed this with these commits:
https://github.com/mostaphaRoudsari/Honeybee/commit/7ad0041298674795711a7e4826eaf37bfc27b21a
https://github.com/mostaphaRoudsari/Honeybee/commit/5c6b1668f766e6cd13bc4597eaedf5ccaca66aaa

I am getting annual surface energy flows that matches all of the way down to 3 decimal places.  If you could vertify that the issue is also fixed on your system after updating the components, that would be great.

Thank you, again, @jacoposartore !

**Closed by chriswmackey** 2016-07-24 00:14 UTC
Labels: EnergyPlus, OpenStudio, question

**Comment by jacoposartore** [comment] 2016-07-25 07:47
@chriswmackey,

Great! Now they are almost identica (0,0001 % error)! Thank you!
