### ISSUE TITLE
HB_HVAC Air details: solution exception:__init__() takes at most 14 arguments (15 given)

### ISSUE THREAD

**Issue by zdenomalik** [mostaphaRoudsari/honeybee#719] opened 2019-01-27 18:32 UTC
Hi, I am running into a problem with the HVAC Air Details component, the simulation won't run and the component says: 1. Solution exception:__init__() takes at most 14 arguments (15 given). Is there a problem on my side or is this happening in someone else's simulations?

**Comment by chriswmackey** [comment] 2019-01-30 13:58
@zdenomalik ,
This issue happens when the version of the _Honeybee Air Detail_ is not correctly matched with the version of _Honeybee_Honeybee_ flying on your canvass.  Update all of your components on you canvass to the same version using the _Ladybug_Update File_ component and everything should work fine.

Also, this is not a bug and so it really does not belong on the github but rather [our forum](https://discourse.ladybug.tools/).  As such, I am closing out this issue here and, if you have any other questions, I recommend asking them on the forum first.  Then, if we determine that the issue is the result of a bug, we can open a github issue.

**Closed by chriswmackey** 2019-01-30 13:58 UTC
