### ISSUE TITLE
Double check setback component in Honeybee

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/honeybee#286] opened 2015-02-22 17:38 UTC
http://www.grasshopper3d.com/group/ladybug/forum/topics/thermostat-setbacks

**Comment by mostaphaRoudsari** [comment] 2015-11-01 17:36
I will check this after addressing #126.

**Comment by mostaphaRoudsari** [comment] 2015-11-04 05:03
This is happening because the josn file doesn't have the key for setback schedules. I'm not sure why is that. Here is the available schedules :
```
'lighting_pri_spc_type',
'infiltration_sch',
'cooling_setpoint_sch',
'occupancy_per_area',
'elec_equip_per_area',
'rgb',
'lighting_w_per_person',
'ventilation_ach',
'lighting_standard',
'ventilation_standard',
'lighting_sec_spc_type',
'gas_equip_per_area',
'infiltration_per_area_ext',
'ventilation_pri_spc_type',
'occupancy_activity_sch',
'lighting_sch',
'occupancy_sch',
'ventilation_per_area',
'lighting_w_per_area',
'ventilation_sec_spc_type',
'ventilation_per_person',
'elec_equip_sch',
'gas_equip_sch',
'heating_setpoint_sch'
```

**Comment by mostaphaRoudsari** [comment] 2015-11-04 05:20
Regardless of the warning the component looks to be working fine and generates the schedule. I think we can close this but I think it's better to have more people looking at this before I close it

![image](https://cloud.githubusercontent.com/assets/2915573/10930176/bccd6d06-8289-11e5-8e8a-03375a04a4ee.png)

**Comment by chriswmackey** [comment] 2015-11-04 12:55
@mostapharoudsari ,

In the year or so that I have been applying this component, it has always worked as intended for the simulation but I have never completely understood the warnings that I get every time that I input vales into the setback.  For this reason, I changed the warnings to cments a couple of months ago.

The way I am explaining it to myself right now, there are some setpoint schedules that govern the  typical operation if the zone and others for design day conditions. The design day schedules never have setbacks and this is why the component complains.

Let me know if this is making sense.

-Chris

**Comment by mostaphaRoudsari** [comment] 2015-11-05 05:05
Since this is working fine I change the lable to enhancement and I will check it later.

**Comment by chriswmackey** [comment] 2017-07-26 14:07
Now that I have gone 2 years with using this feature, I feel confident that it's all working correctly.  I'm going to close it out!

**Closed by chriswmackey** 2017-07-26 14:07 UTC
Labels: EnergyPlus, enhancement, OpenStudio
