### ISSUE TITLE
Question of Modeling Prismatic Film with xml file

### ISSUE THREAD

**Issue by DavidZTian** [mostaphaRoudsari/honeybee#635] opened 2017-07-08 02:24 UTC
Hi everyone, I am tying to model prismatic film for daylighting. I used the Honeybee_Radiance BSDF Material with the Film3M_145x1297_9142012_t.xml as well as real direct and diffuse radiation data. When I compared simulated illumiance data with real illumiance distribution data, the simulated data are way off the measured data. I asked Andy McNeil about this problem. 
Andy provided the following suggestion: "It's not advisable to use BSDF material for the window in a daylight coefficient simulation (which is the method used by ladybug/honeybee). The reason is that the DC method (and most annual simulation methods) don't include a suns for sampling, but instead use discretized skies. The sampling of suns, which use a light material, is deterministic - meaning a ray is purposely sent to the sun. For skies, Radiance uses stochastic sampling, which means rays are sent in random directions. When a ray hits a BSDF material, Radiance uses importance sampling, meaning rays are still random, but more likely to be sent in directions that contribute more to the result for the incident ray direction based on BSDF value. This works well when there is minor variation over the hemispherical source. However, when the radiance of the sun is added to a sky patch, that patch has 4000x higher value than the other patches. And if BSDF importance sampling doesn't send many or any rays in the direction of that patch, the result can be way off."

I am wondering whether the **Honeybee_Radiance BSDF Material** really works or there should be some update for this? Maybe Mostapha or someone else who had tried this can give some help? Thanks a lot.

David

**Comment by sariths** [comment] 2017-07-08 16:22
As a developer for Honeybee, I can tell you that this -"It's not advisable to use BSDF material for the window in a daylight coefficient simulation (which is the method used by ladybug/honeybee"- is only partially correct. You can do a  [point-in-time simulation using climate-based sky](http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Honeybee_Grid-based_Daylight_Simulation_Example_II&slide=0&scale=1&offset=-8.080258488441586,-1.0734556716499242) and the BSDFs will work just fine. The issue is with annual simulations where the calculations are performed using Daysim (which, unfortunately, is not BSDF compatible).

**Comment by DavidZTian** [comment] 2017-07-09 11:11
Thanks a lot Sariths for the clarification! I think this clarification will also be of help to all Honeybee fans who want to use this BSDF Material function. Currently I am using this function with climate sky and the Film3M_145x1297_9142012_t.xml to model the point-in-time illuminance distribution in one zone. Unfortunately the simulated point-in-time illumiance distribution results are way off the real illuminance measured in space. I am trying to figure the problem is due to the xml file problem or some other aspects.

**Comment by DavidZTian** [comment] 2017-07-09 11:12
Thanks a lot Sariths for the clarification! I think this clarification will also be of help to all Honeybee fans who want to use this BSDF Material function. Currently I am using this function with climate sky and the Film3M_145x1297_9142012_t.xml to model the point-in-time illuminance distribution in one zone. Unfortunately the simulated point-in-time illumiance distribution results are way off the real illuminance measured in space. I am trying to figure out the problem is due to the xml file or some other aspects.

**Comment by mostaphaRoudsari** [comment] 2017-07-09 15:59
@DavidZTian, A couple of questions that you can ask yourself to debug your model.

1. What are the radiance parameters / options are set to? Are they high enough?
2. Did you calibrate the sky against the measured sky?
3. What are the differences between measured and modeled results? Is the pattern similar but the values are different or you don't get the excepted pattern?
4. Did you try to also run an image-based analysis and see how does the scene look like and if it matches the real scene.

**Comment by mostaphaRoudsari** [comment] 2017-07-09 16:00
In any case discussion is better to happen in the forum as it's not related to the development.

**Comment by sariths** [comment] 2017-07-09 16:06
@DavidZTian Concurring with all the points that @mostaphaRoudsari made, I'd like to add that one reliable way to validate/compare such a measurement would be to plugin the values of direct-normal and horizontal diffuse radiation in the place of values that you are currently getting from a TMY data set. There are a few studies conducted by LBNL and the Fraunhofer institute where they delve into the details of conducting such validations.

**Comment by DavidZTian** [comment] 2017-07-10 07:06
Thanks Mostaoha and Sariths for your suggestions.  1. The Radiance bounce is set as 4; 2. I dont know how to check the sky against the measured sky, can you please provide a method?; 3. The measured illuminances higher than simulated values are mainly located in the inner part of the space, with depth of aroud 20 meters from windows, and are also in the place close to the window (1m from window); 4. I have not setup the image-based analysis yet. I am still trying to find a good xml file to test as the previous xml maynot be appropriate for my study.  I  used the BSDF material viewer to open Film3M_145x1297_9142012_t.xml file but the file seems odd as I cannot see the patten properties. Do you know where can I find a updated one? I have contacted several people in 3M but have not received one yet. Thanks.

**Comment by sariths** [comment] 2017-07-10 17:57
Hi @DavidZTian, 

Typically, one has to measure/obtain direct-normal and diffuse horizontal radiation values and then create a sky definition from that. This [dissertation](https://etda.libraries.psu.edu/files/final_submissions/14201) contains a fairly detailed description about how the author went about doing the validation with simple instruments. I would like point out that validating daylighting simulations with measurements is a fairly involved and non-trivial process. You are unlikely to get too far through crowd-sourcing.

**Comment by DavidZTian** [comment] 2017-08-03 09:28
Thanks Sariths for the guidance. For my research, I have got the dierct-normal and diffuse raidation values from National weather station and create the sky definiation in the epw weather file. I briefly read the dissertation you referred. But for my case, the reaseach building been measured is basically shading FREE from surrouding buildings or trees. During my visit in HongKong the past two weeks I discussed the issues with a research and found the major possible problem is in the file of Film3M_145x1297_9142012_t.xml itself. We cannot open it with the Windows version of LBNL BSDFViewer. However, we can view the file content in the Mac version of LBNL BSDF Viewer 1.3. By opening the xml file in BSDF viewer, we found the definded Visible Transmittance of the 3M prismatic film are very low. This data may explain well why the indoor illumiance levels are so low when we use the Film3M_145x1297_9142012_t.xml in radiance simulations. 
More interesting, when I came back from Hongkong I bought a Macbook Air use the BSDFViewer Mac version. But when I installed the BSDFViewer Mac version, the same problem in the Windows version happen again and I cannot open the xml file and got a waring saying the file cannot be openned because there is no data view (XSLT).

**Comment by sariths** [comment] 2017-08-03 15:55
Hi @DavidZTian , couple of things. The radiation data in that dissertation was actually collected at a weather data measuring station. The experiments themselves were performed to determine shading related parameters. So, the measurement values as relating to weather still apply. It's just that in your research might not have the same set of confounding factors that Reza (the author) was working with.

The issue with BSDF viewer is fairly well known. It has been updated in a while. You can read more about it by searching through the archives of the Radiance mailing list. (Google:  bsdf viewer  site:www.radiance-online.org )

**Comment by chriswmackey** [comment] 2018-01-14 22:26
I am closing this out as an issue since this if more of a discussion.  If anyone wishes to continue it, this should be done on the forums as @mostaphaRoudsari suggests.

**Closed by chriswmackey** 2018-01-14 22:26 UTC
Labels: Radiance, question
